RULES = {
    'DQ-SRC-001': {'dimension':'Completeness','scope':'Source','severity':'CRITICAL','action':'Stop ingestion'},
    'DQ-SRC-002': {'dimension':'Schema','scope':'Source','severity':'CRITICAL','action':'Stop ingestion'},
    'DQ-SRC-004': {'dimension':'Uniqueness','scope':'Source','severity':'HIGH','action':'Quarantine affected records'},
    'DQ-SRC-005': {'dimension':'Referential Integrity','scope':'Source','severity':'HIGH','action':'Block affected dataset'},
    'DQ-SRC-006': {'dimension':'Validity','scope':'Source','severity':'HIGH','action':'Quarantine invalid records'},
    'DQ-RAW-001': {'dimension':'Completeness','scope':'Raw','severity':'CRITICAL','action':'Stop downstream processing'},
    'DQ-RAW-002': {'dimension':'Integrity','scope':'Raw','severity':'CRITICAL','action':'Stop downstream processing'},
    'DQ-RAW-003': {'dimension':'Immutability','scope':'Raw','severity':'CRITICAL','action':'Stop ingestion'},
    'DQ-BRZ-001': {'dimension':'Completeness','scope':'Bronze','severity':'CRITICAL','action':'Block downstream processing'},
    'DQ-BRZ-002': {'dimension':'Reconciliation','scope':'Bronze','severity':'HIGH','action':'Block affected dataset'},
    'DQ-BRZ-003': {'dimension':'Schema','scope':'Bronze','severity':'HIGH','action':'Block affected dataset'},
    'DQ-BRZ-004': {'dimension':'Transformation','scope':'Bronze','severity':'HIGH','action':'Block affected dataset'},
    'DQ-SLV-001': {'dimension':'Schema','scope':'Silver','severity':'CRITICAL','action':'Block publication'},
    'DQ-SLV-002': {'dimension':'CDC Integrity','scope':'Silver','severity':'CRITICAL','action':'Reject event'},
    'DQ-SLV-003': {'dimension':'CDC Integrity','scope':'Silver','severity':'HIGH','action':'Reject event'},
    'DQ-SLV-004': {'dimension':'CDC Ordering','scope':'Silver','severity':'HIGH','action':'Quarantine batch'},
    'DQ-SLV-005': {'dimension':'Idempotency','scope':'Silver','severity':'CRITICAL','action':'Reject duplicate'},
    'DQ-SLV-006': {'dimension':'Referential Integrity','scope':'Silver','severity':'HIGH','action':'Block affected dataset'},
    'DQ-GOLD-001': {'dimension':'Completeness','scope':'Gold','severity':'CRITICAL','action':'Block publication'},
    'DQ-GOLD-002': {'dimension':'Grain','scope':'Gold','severity':'CRITICAL','action':'Block publication'},
    'DQ-GOLD-003': {'dimension':'Reconciliation','scope':'Gold','severity':'CRITICAL','action':'Block publication'},
    'DQ-GOLD-004': {'dimension':'Validity','scope':'Gold','severity':'HIGH','action':'Block affected product'},
    'DQ-GOLD-005': {'dimension':'Uniqueness','scope':'Gold','severity':'CRITICAL','action':'Block publication'},
    'DQ-GOLD-006': {'dimension':'Schema','scope':'Gold','severity':'CRITICAL','action':'Block publication'}
}
